#!/usr/bin/env python3
"""
change-impact-e2e-bridge.py
SCT 工具 5：把 acceptance.yaml 的 e2e 段 + change-impact.md 的命中场景 → Playwright spec.js

归属：Speckit 扩展 `sct` 内置实现（v1.0-W2 / 自包含）

输入：
  --spec        acceptance.yaml 路径
  --impact      change-impact.md 路径（W1 可选，缺则全部 P0/P1 跑）
  --out         生成的 spec.js 输出目录

输出（三类产物）：
  1. {out_dir}/{scenario_id}.spec.js        Playwright 自动化脚本
  2. {out_dir}/E2E_TESTCASES.md             人工测试案例（给测试人员执行/评审用，
                                            模板：templates/e2e-testcases-template.md）
  3. {out_dir}/_intent_tests.json           意图驱动测试导出（对接 UI 自动化测试平台，
                                            模板：templates/intent-test-template.json）
  + 摘要 {out_dir}/_summary.json

用法：
  python $SCT_EXT_HOME/scripts/change-impact-e2e-bridge.py \\
    --spec specs/001-batch-import/acceptance.yaml \\
    --impact change-impact.md \\
    --out e2e/auto_generated/

W1 限制：
  - 仅支持 action.type=upload_file
  - 仅支持 assertion.type=ui_message
  - 仅支持 pre_steps=login/navigate:xxx
  - 真实 Playwright config + fixtures 由项目侧维护
"""
import argparse
import json
import re
import sys
from datetime import datetime
from pathlib import Path

import yaml


# ====== Playwright 模板（W1 demo） ======
PLAYWRIGHT_TEMPLATE = """// Auto-generated by $SCT_EXT_HOME/scripts/change-impact-e2e-bridge.py
// DO NOT EDIT - 任何修改会被下次生成覆盖
// Scenario: {scenario_id} | Priority: {priority} | Feature: {feature_id}
// Source: {source_spec}

const {{ test, expect }} = require('@playwright/test');
const path = require('path');
const {{ login }} = require('../shared/login');

test.describe('{feature_id} - {feature_name}', () => {{
  test('{scenario_id} - {scenario_title}', async ({{ page }}) => {{
    // 1. 前置步骤
{pre_steps_code}

    // 2. 触发动作（{action_type}）
{action_code}

    // 3. 断言（{assertion_type}）
{assertion_code}
  }});
}});
"""


def parse_args():
    p = argparse.ArgumentParser(description='change-impact → Playwright e2e bridge')
    p.add_argument('--spec', required=True, help='acceptance.yaml 路径')
    p.add_argument('--impact', help='change-impact.md 路径（可选）')
    p.add_argument('--out', required=True, help='spec.js 输出目录')
    p.add_argument('--dry-run', action='store_true', help='只打印不写文件')
    p.add_argument('--include-p2', action='store_true',
                   help='F-15 修复：无 impact 文件时也包含 P2 场景（默认只跑 P0/P1）')
    return p.parse_args()


def load_spec(path: str) -> dict:
    raw = Path(path).read_text(encoding='utf-8')
    # F-16 修复：pre_steps 若写成 inline flow 且含 '?'（如 [login, navigate:/x?y=1]），
    # PyYAML 会把 '?' 当 complex-key 指示符而解析失败。预处理把单行
    # 'pre_steps: [a, b]' 拆成 block 序列（缩进跟随原行）再交给 safe_load。
    raw = re.sub(
        r'(^[ \t]*)(pre_steps\s*:\s*)\[(.*?)\]',
        lambda m: m.group(1) + m.group(2) + '\n' + '\n'.join(
            f"{m.group(1)}  - {x.strip()}" for x in m.group(3).split(',') if x.strip()),
        raw,
        flags=re.M | re.S,
    )
    try:
        return yaml.safe_load(raw)
    except Exception as e:
        raise SystemExit(
            f"YAML 解析失败: {e}\n"
            f"提示: 若 pre_steps 用了含 '?' 的 inline flow（如 [login, navigate:/x?y=1]），"
            f"请改用 block 序列：\n"
            f"      pre_steps:\n"
            f"        - login\n"
            f"        - navigate:/x?y=1\n")


def collect_scenarios(spec: dict) -> list:
    """遍历 features，把所有带 e2e 段的 scenario 拍平"""
    out = []
    for feat in spec.get('features', []):
        for sc in feat.get('acceptance_scenarios', []):
            if 'e2e' not in sc:
                continue
            out.append({
                'feature_id': feat['id'],
                'feature_name': feat['name'],
                **sc,
            })
    return out


def filter_by_impact(scenarios: list, impact_path: str | None, include_p2: bool = False) -> list:
    """根据 change-impact.md 过滤（无 impact 时：默认 P0/P1，--include-p2 时含 P2）"""
    if not impact_path or not Path(impact_path).exists():
        # 无 impact：F-15 修复，--include-p2 时含 P2，否则 P0/P1
        return [s for s in scenarios
                if s['e2e'].get('priority') in ('P0', 'P1', 'P2' if include_p2 else '')]

    # 解析 change-impact.md（F-15：识别 P0/P1/P2 行；优先级可能加粗或不加粗，统一去 * 归一化）
    impacted_ids = set()
    for line in Path(impact_path).read_text(encoding='utf-8').splitlines():
        if '|' not in line:
            continue
        cols = [c.strip() for c in line.split('|')]
        # 形如 | **P0** | F001-1 | ... | （与 consistency-check.parse_impact_priorities 口径一致）
        if len(cols) >= 3:
            pri = cols[1].strip().strip('*').strip()
            if pri in ('P0', 'P1', 'P2' if include_p2 else ''):
                impacted_ids.add(cols[2])

    return [s for s in scenarios if s['id'] in impacted_ids]


def render_pre_steps(pre_steps: list) -> str:
    """pre_steps → JS 代码"""
    lines = []
    for step in pre_steps:
        if step == 'login':
            lines.append("    await login(page);")
        elif step.startswith('navigate:'):
            path = step.split(':', 1)[1]
            lines.append(f"    await page.goto('{path}');")
        else:
            lines.append(f"    // TODO: 未知 pre_step {step!r}")
    return '\n'.join(lines) if lines else "    // (无前置步骤)"


def render_action(action: dict, fixture: dict | None) -> str:
    """action → Playwright 代码

    F-13 修复：不止 upload_file，支持常见 UI 动作：
      - upload_file           文件上传（file_input / drag_drop）
      - click / double_click  点击（target 支持 css 选择器或文本）
      - fill                  输入框填值
      - navigate              页面跳转
      - batch_confirm_nodes   批量确认（循环点击确认按钮直到不可点）
    """
    atype = action.get('type', '')
    if atype == 'upload_file':
        file_ref = action.get('file_ref', '')
        # 规范化：去除可能的 "fixtures/" 前缀（SoT 允许两种写法）
        file_ref = file_ref.removeprefix('fixtures/')
        method = action.get('method', 'file_input')
        # 取 fixture 目录（约定：fixtures 在 e2e/fixtures/ 下，spec.js 在 e2e/auto_generated/）
        if method == 'drag_drop':
            return f"""    const filePath = path.join(__dirname, '..', 'fixtures', '{file_ref}');
    const dropZone = page.locator('.dropzone, [data-testid="upload-area"]').first();
    await dropZone.setInputFiles(filePath);  // Playwright dropzone 兜底写法"""
        return f"""    const filePath = path.join(__dirname, '..', 'fixtures', '{file_ref}');
    const fileInput = page.locator('input[type="file"]').first();
    await fileInput.setInputFiles(filePath);"""
    if atype in ('click', 'double_click', 'double_click_node'):
        target = action.get('target', action.get('selector', ''))
        if not target:
            return f"    // TODO: action.type={atype} 缺少 target/selector"
        if target.startswith(('text=', 'css=', 'xpath=', 'role=')):
            loc = f"page.locator('{target}')"
        else:
            loc = f"page.getByText('{target}').first()"
        meth = 'dblclick' if atype in ('double_click', 'double_click_node') else 'click'
        return f"    await {loc}.{meth}();"
    if atype == 'fill':
        target = action.get('target', action.get('selector', ''))
        value = action.get('value', action.get('text', ''))
        if not target:
            return f"    // TODO: action.type=fill 缺少 target/selector"
        loc = (f"page.locator('{target}')" if target.startswith(('css=', 'xpath=', 'role='))
               else f"page.getByPlaceholder('{target}').first()")
        return f"    await {loc}.fill('{value}');"
    if atype == 'navigate':
        return f"    await page.goto('{action.get('url', '')}');"
    if atype == 'batch_confirm_nodes':
        btn = action.get('confirm_selector', action.get('target', 'text=确认'))
        return f"""    // 批量确认：循环点击"确认"直到不再出现
    let confirmBtn = page.locator('{btn}').first();
    while (await confirmBtn.count()) {{
      await confirmBtn.click();
      await page.waitForTimeout(200);
      confirmBtn = page.locator('{btn}').first();
    }}"""
    return f"    // TODO: action.type={atype} 暂未实现"


def render_assertion(assertion: dict) -> str:
    """assertion → Playwright 断言代码

    F-14 修复：不止 ui_message，支持常见断言类型：
      - ui_message  页面出现指定文本
      - ui_visible  选择器对应元素可见
      - url_contains 当前 URL 包含指定片段
    """
    atype = assertion.get('type', '')
    timeout = assertion.get('timeout', 5000)
    if atype == 'ui_message':
        text = assertion.get('text', '')
        return f"""    await expect(page.getByText('{text}').first())
      .toBeVisible({{ timeout: {timeout} }});"""
    if atype == 'ui_visible':
        sel = assertion.get('selector', assertion.get('target', ''))
        if not sel:
            return "    // TODO: assertion.type=ui_visible 缺少 selector"
        return f"""    await expect(page.locator('{sel}').first())
      .toBeVisible({{ timeout: {timeout} }});"""
    if atype == 'url_contains':
        frag = assertion.get('fragment', assertion.get('text', ''))
        return f"""    await expect(page).toHaveURL(new RegExp('{frag}'));"""
    return f"    // TODO: assertion.type={atype} 暂未实现"


def render_scenario(scenario: dict, source_spec: str) -> str:
    e2e = scenario['e2e']
    return PLAYWRIGHT_TEMPLATE.format(
        scenario_id=scenario['id'],
        priority=e2e.get('priority', 'P2'),
        feature_id=scenario['feature_id'],
        feature_name=scenario['feature_name'],
        scenario_title=scenario.get('when', '')[:50],
        source_spec=source_spec,
        pre_steps_code=render_pre_steps(e2e.get('pre_steps', [])),
        action_type=e2e['action'].get('type', 'unknown'),
        action_code=render_action(e2e['action'], e2e.get('fixture')),
        assertion_type=e2e['assertion'].get('type', 'unknown'),
        assertion_code=render_assertion(e2e['assertion']),
    )


# =====================================================================
# 产物 2：人工测试案例文档（E2E_TESTCASES.md，给测试人员用）
# =====================================================================

def humanize_pre_steps(pre_steps: list) -> list:
    """pre_steps → 人类可读步骤"""
    out = []
    for step in pre_steps:
        if step == 'login':
            out.append('登录系统')
        elif step.startswith('navigate:'):
            out.append(f"打开页面 {step.split(':', 1)[1]}")
        else:
            out.append(f"执行前置动作 {step}")
    return out


def humanize_action(action: dict) -> str:
    """action → 人类可读操作（F-13 扩展）"""
    atype = action.get('type')
    if atype == 'upload_file':
        file_ref = action.get('file_ref', '（未指定文件）')
        return f"在文件上传控件选择 `{file_ref}` 并提交"
    if atype in ('click', 'double_click'):
        return f"{'双击' if atype == 'double_click' else '点击'}元素 `{action.get('target', '')}`"
    if atype == 'fill':
        return f"在 `{action.get('target', '')}` 输入 `{action.get('value', '')}`"
    if atype == 'navigate':
        return f"打开页面 `{action.get('url', '')}`"
    if atype == 'batch_confirm_nodes':
        return f"批量确认节点（循环点击 `{action.get('confirm_selector', '确认')}`）"
    return f"执行操作 {atype or 'unknown'}"


def humanize_assertion(assertion: dict) -> str:
    """assertion → 人类可读预期（F-14 扩展）"""
    atype = assertion.get('type')
    if atype == 'ui_message':
        return f"页面出现提示文本「{assertion.get('text', '')}」"
    if atype == 'ui_visible':
        return f"元素 `{assertion.get('selector', '')}` 可见"
    if atype == 'url_contains':
        return f"URL 包含 `{assertion.get('fragment', '')}`"
    return f"验证 {atype or 'unknown'}"


def case_type_of(scenario: dict) -> str:
    """判断案例类型：正例（正常路径）/ 反例（异常/边界/非法输入）。

    优先级：SoT 显式 `case_type` > 启发式（then 文本含拒绝/失败/报错/异常/不允许/无权限 等词 → 反例）。
    """
    e2e = scenario.get('e2e', {})
    explicit = e2e.get('case_type')
    if explicit in ('positive', 'negative', '正例', '反例'):
        return '正例' if explicit in ('positive', '正例') else '反例'
    then = scenario.get('then', '') or ''
    negative_hints = ('拒绝', '失败', '报错', '错误', '异常', '不允许', '禁止',
                      '无权限', '无效', '超限', '不存在', '不可', '提示错误')
    return '反例' if any(h in then for h in negative_hints) else '正例'


def gen_testcases_doc(scenarios: list, source_spec: str, impact_ref: str | None) -> str:
    """生成人工测试案例文档（模板：templates/e2e-testcases-template.md）"""
    now = datetime.now().isoformat(timespec='seconds')
    p0 = sum(1 for s in scenarios if s['e2e'].get('priority') == 'P0')
    p1 = sum(1 for s in scenarios if s['e2e'].get('priority') == 'P1')
    p2 = len(scenarios) - p0 - p1

    L = ['# E2E 测试案例（人工执行版）', '']
    L.append(f"**Generated**: {now}  ")
    L.append(f"**SoT**: `{source_spec}`  ")
    L.append(f"**Impact 来源**: `{impact_ref or '未提供（全量 P0/P1）'}`  ")
    L.append(f"**自动化脚本目录**: `e2e/auto_generated/`  ")
    L.append(f"**用例总数**: {len(scenarios)}（P0={p0}, P1={p1}, P2={p2}）")
    L.append('')
    L.append('> 使用说明：')
    L.append('> 1. 每个案例与同名 `{案例ID}.spec.js` 自动化脚本一一对应，可人工执行也可自动执行')
    L.append('> 2. 「执行结果」由测试人员回填：通过 / 失败（附缺陷单号）')
    L.append('> 3. 案例的 Given/When/Then 来自 SoT 验收场景原文，修改需求请先改 SoT')
    L.append('')

    for sc in scenarios:
        e2e = sc['e2e']
        sid = sc['id']
        pri = e2e.get('priority', 'P2')
        L.append('---')
        L.append('')
        L.append(f"## 用例 {sid}：{sc.get('when', '')[:50]}")
        L.append('')
        L.append('| 项目 | 内容 |')
        L.append('|------|------|')
        L.append(f"| 案例编号 | {sid} |")
        L.append(f"| 案例类型 | **{case_type_of(sc)}**（正例=正常路径 / 反例=异常·边界·非法输入） |")
        L.append(f"| 案例优先级 | **{pri}** |")
        L.append(f"| 所属模块 | {sc['feature_id']} {sc['feature_name']} |")
        L.append(f"| 对应自动化 | `{sid}.spec.js` |")
        L.append('')
        L.append(f"**案例意图**：{sc.get('given', '')}时，{sc.get('when', '')}，应{sc.get('then', '')}")
        L.append('')
        L.append('**前置条件（Given）**：')
        L.append(f"- {sc.get('given', '')}")
        file_ref = e2e.get('action', {}).get('file_ref')
        if file_ref:
            L.append(f"- 准备测试数据 `e2e/fixtures/{file_ref.removeprefix('fixtures/')}`")
        L.append('')
        L.append('**测试步骤（When）**：')
        steps = humanize_pre_steps(e2e.get('pre_steps', []))
        steps.append(humanize_action(e2e.get('action', {})))
        for i, st in enumerate(steps, 1):
            L.append(f"{i}. {st}")
        L.append('')
        L.append('**预期结果（Then）**：')
        L.append(f"- {humanize_assertion(e2e.get('assertion', {}))}")
        L.append(f"- {sc.get('then', '')}")
        if file_ref:
            L.append('')
            L.append(f"**测试数据**：`e2e/fixtures/{file_ref.removeprefix('fixtures/')}`")
        L.append('')
        L.append('**执行结果**：（测试人员填写）☐ 通过 ☐ 失败　缺陷单：________')
        L.append('')

    # 执行汇总表（回填）
    L.append('---')
    L.append('')
    L.append('## 执行汇总（测试人员回填）')
    L.append('')
    L.append('| 案例编号 | 案例类型 | 优先级 | 执行方式（人工/自动） | 结果 | 缺陷单 | 备注 |')
    L.append('|---------|---------|--------|----------------------|------|--------|------|')
    for sc in scenarios:
        L.append(f"| {sc['id']} | {case_type_of(sc)} | {sc['e2e'].get('priority', 'P2')} | | | | |")
    L.append('')
    L.append('> 放行标准：P0 全部通过；P1 失败需记录缺陷并限期修复。')
    return '\n'.join(L)


# =====================================================================
# 产物 3：意图驱动测试导出（_intent_tests.json，对接 UI 自动化测试平台）
# =====================================================================

def gen_intent_export(scenarios: list, source_spec: str, impact_ref: str | None) -> dict:
    """生成意图驱动测试导出（模板：templates/intent-test-template.json）

    平台按 intent + Given/When/Then 驱动执行与编排；
    字段与 SoT 验收场景一一对应，保证「意图 = 真相」。
    """
    cases = []
    for sc in scenarios:
        e2e = sc['e2e']
        cases.append({
            'id': sc['id'],
            'feature_id': sc['feature_id'],
            'feature_name': sc['feature_name'],
            'priority': e2e.get('priority', 'P2'),
            'intent': f"{sc.get('given', '')}时，{sc.get('when', '')}，应{sc.get('then', '')}",
            'given': sc.get('given', ''),
            'when': sc.get('when', ''),
            'then': sc.get('then', ''),
            'pre_steps': e2e.get('pre_steps', []),
            'action': e2e.get('action', {}),
            'assertion': e2e.get('assertion', {}),
            'automation_script': f"{sc['id']}.spec.js",
            'tags': ['regression', sc['feature_id'].lower()],
        })
    return {
        'export_version': '1.0',
        'generated_at': datetime.now().isoformat(timespec='seconds'),
        'source_spec': source_spec,
        'impact_source': impact_ref or '',
        'test_type': 'intent-driven-ui',
        'cases': cases,
    }


def main():
    args = parse_args()

    spec = load_spec(args.spec)
    all_scenarios = collect_scenarios(spec)
    target_scenarios = filter_by_impact(all_scenarios, args.impact, args.include_p2)

    if not target_scenarios:
        print(f"⚠️  无可生成场景（spec 共 {len(all_scenarios)} 个含 e2e 段的 scenario，过滤后 0 个）",
              file=sys.stderr)
        sys.exit(1)

    out_dir = Path(args.out)
    if not args.dry_run:
        out_dir.mkdir(parents=True, exist_ok=True)

    summary = {
        'total_scenarios': len(all_scenarios),
        'generated_count': 0,
        'skipped_count': len(all_scenarios) - len(target_scenarios),
        'files': [],
    }

    for sc in target_scenarios:
        content = render_scenario(sc, source_spec=args.spec)
        filename = f"{sc['id']}.spec.js"
        if args.dry_run:
            print(f"--- {filename} ---")
            print(content)
            print()
        else:
            (out_dir / filename).write_text(content, encoding='utf-8')
            summary['files'].append(filename)
            summary['generated_count'] += 1
            print(f"✅ 生成 {filename} (priority={sc['e2e'].get('priority')})")

    if not args.dry_run:
        # 产物 2：人工测试案例文档（给测试人员执行/评审用）
        testcases_md = gen_testcases_doc(target_scenarios, args.spec, args.impact)
        (out_dir / 'E2E_TESTCASES.md').write_text(testcases_md, encoding='utf-8')
        summary['testcases_doc'] = 'E2E_TESTCASES.md'

        # 产物 3：意图驱动测试导出（对接 UI 自动化测试平台）
        intent_export = gen_intent_export(target_scenarios, args.spec, args.impact)
        (out_dir / '_intent_tests.json').write_text(
            json.dumps(intent_export, ensure_ascii=False, indent=2),
            encoding='utf-8',
        )
        summary['intent_export'] = '_intent_tests.json'

        (out_dir / '_summary.json').write_text(
            json.dumps(summary, ensure_ascii=False, indent=2),
            encoding='utf-8',
        )
        print(f"\n📊 摘要: {summary['generated_count']} 个生成 / {summary['skipped_count']} 个跳过")
        print(f"📝 人工测试案例: {out_dir / 'E2E_TESTCASES.md'}")
        print(f"🧠 意图驱动导出: {out_dir / '_intent_tests.json'}（对接 UI 自动化测试平台）")
        print(f"📁 输出目录: {out_dir.resolve()}")


if __name__ == '__main__':
    main()
